### ISSUE TITLE
Note that "authorization" parameter must not be renamed

### ISSUE THREAD

**Issue by debuglevel** [micronaut-guides/micronaut-security-basicauth#6]
It might be nice to note that one *must not* rename the `authorization` parameter of the `@Client` (as the parameter name automagically is used for the HTTP-Header).

**Comment by sdelamo** [comment]
if you wish to change the parameter name you can qualify the `@Header` annotation with a value. e.g. 

`String home(@Header(HttpHeaders.AUTHORIZATION) String foo);`
